# syntax=docker/dockerfile:1
FROM scratch
ARG GIT_COMMIT
ARG GH_WORKSPACE

WORKDIR /config

COPY target/docker/release/rtabby-web-api /
COPY users.exemple.yml .
COPY web/ /www/web/
ENV STATIC_FILES_BASE_DIR=/www/web/
ENV GIT_COMMIT=$GIT_COMMIT

CMD ["/rtabby-web-api"]
