services:
  rtabby:
    container_name: rtabby-web-api

    image: ghcr.io/clem-fern/rtabby-web-api:latest
    # Minimal image without third party login
    #image: ghcr.io/clem-fern/rtabby-web-api:latest-minimal

    # Build image from local rtabby repository
    #build:
    #  context: .
    #  args:
    #    - GIT_COMMIT=${GIT_COMMIT}
    # Optional: Minimal image without third party login
    #    - FEATURE_FLAGS=-F|mysql-bundle

    # If running as root, setup your user/volume owner UID and GID
    #user: "1000:1000"

    cap_add:		
      - "CAP_DAC_OVERRIDE"
    cap_drop: ['ALL']
    read_only: true

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://tabby:tabby@db/tabby
      #- GITHUB_APP_CLIENT_ID=
      #- GITHUB_APP_CLIENT_SECRET=
      #- GITLAB_APP_CLIENT_ID=
      #- GITLAB_APP_CLIENT_SECRET=
      #- GOOGLE_APP_CLIENT_ID=
      #- GOOGLE_APP_CLIENT_SECRET=
      #- MICROSOFT_APP_CLIENT_ID=
      #- MICROSOFT_APP_CLIENT_SECRET=

    volumes:
      - ./config:/config
    networks:
      - frontend
      - default
    depends_on:
      db:
        condition: 'service_healthy'
  db:
    container_name: rtabby-database
    image: mariadb:latest

    read_only: true
    
    tmpfs:
      - /run/mysqld/
      - /tmp
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_MYSQL_LOCALHOST_USER=true
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=tabby
      - MARIADB_USER=tabby
      - MARIADB_PASSWORD=tabby
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 6s
volumes:
  database:
networks:
  default:
    name: rtabby_net_backend
    internal: true
  frontend:
    name: rtabby_net_frontend