services:
  rtabby:
    container_name: rtabby-web-api

    image: ghcr.io/clem-fern/rtabby-web-api:sqlite
    # Minimal image without third party login
    #image: ghcr.io/clem-fern/rtabby-web-api:sqlite-minimal

    # Build image from local rtabby repository
    #build:
    #  context: .
    #  args:
    #    - FEATURE_FLAGS=-F|sqlite-bundle|-F|all-login
    #    - GIT_COMMIT=${GIT_COMMIT}
    # Optional: Minimal image without third party login
    #    - FEATURE_FLAGS=-F|sqlite-bundle

    # If running as root, setup your user/volume owner UID and GID
    #user: "1000:1000"

    cap_add:		
      - "CAP_DAC_OVERRIDE"
    cap_drop: ['ALL']
    read_only: true

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///config/db.sqlite
      #- GITHUB_APP_CLIENT_ID=
      #- GITHUB_APP_CLIENT_SECRET=
      #- GITLAB_APP_CLIENT_ID=
      #- GITLAB_APP_CLIENT_SECRET=
      #- GOOGLE_APP_CLIENT_ID=
      #- GOOGLE_APP_CLIENT_SECRET=
      #- MICROSOFT_APP_CLIENT_ID=
      #- MICROSOFT_APP_CLIENT_SECRET=
      #- OIDC_APP_CLIENT_ID=
      #- OIDC_APP_CLIENT_SECRET=
      #- OIDC_APP_CONFIG_URL=
    volumes:
      - ./config:/config
    networks:
      - frontend
networks:
  frontend:
    name: rtabby_net_frontend