services:
  rtabby:
    container_name: rtabby-web-api
    #build:
    #  context: .
    #  dockerfile: Dockerfile-sqlite
    image: ghcr.io/clem-fern/rtabby-web-api:sqlite

    # If running as root, setup your user/volume owner UID and GID
    #user: "1000:1000"

    cap_add:		
      - "CAP_DAC_OVERRIDE"
    cap_drop: ['ALL']
    read_only: true

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///config/db.sqlite
    volumes:
      - ./config:/config
networks:
  default:
    name: rtabby_net_frontend