# syntax=docker/dockerfile:1
FROM rust:1.73-alpine AS builder
WORKDIR /build
COPY . .
RUN apk add --no-cache build-base && \
    cargo build --target=x86_64-unknown-linux-musl --release --no-default-features -F sqlite-bundle

FROM scratch

WORKDIR /config

COPY --from=builder /build/target/x86_64-unknown-linux-musl/release/rtabby-web-api /
COPY --from=builder /build/users.exemple.yml .
COPY --from=builder /build/web/static /config/web/static

CMD ["/rtabby-web-api"]
