services:
  tlss:
    container_name: tlss
    #build: .
    image: tabby-light-settings-sync
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://tabby:tabby@db/tabby
    volumes:
      - ./config:/config
    depends_on:
      db:
        condition: 'service_healthy'
  db:
    container_name: tlss-database
    image: mariadb:latest
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_MYSQL_LOCALHOST_USER=true
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=tabby
      - MARIADB_USER=tabby
      - MARIADB_PASSWORD=tabby
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 6s
volumes:
  database: