# syntax=docker/dockerfile:1
FROM scratch
ARG GIT_COMMIT
ARG GH_WORKSPACE

WORKDIR /config

COPY $GH_WORKSPACE/target/ci/release/rtabby-web-api /
COPY $GH_WORKSPACE/users.exemple.yml .
COPY $GH_WORKSPACE/web/ /www/web/
ENV STATIC_FILES_BASE_DIR=/www/web/
ENV GIT_COMMIT=$GIT_COMMIT

CMD ["/rtabby-web-api"]
