services:
  rtabby-sqlite:
    container_name: rtabby-web-api-sqlite
    build:
      context: .
      args:
        - FEATURE_FLAGS=--no-default-features|-F|sqlite-bundle|-F|github-login|-F|gitlab-login
    # image: ghcr.io/clem-fern/rtabby-web-api:sqlite

    # If running as root, setup your user/volume owner UID and GID
    #user: "1000:1000"

    cap_add:		
      - "CAP_DAC_OVERRIDE"
    cap_drop: ['ALL']
    read_only: true

    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config:/config
    networks:
      - frontend

  rtabby:
    container_name: rtabby-web-api
    build:
      context: .
      args:
        - FEATURE_FLAGS=-F|mysqlclient-static|-F|github-login
    # image: ghcr.io/clem-fern/rtabby-web-api

    # If running as root, setup your user/volume owner UID and GID
    #user: "1000:1000"

    env_file:
      - .env
    cap_add:		
      - "CAP_DAC_OVERRIDE"
    cap_drop: ['ALL']
    read_only: true

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://tabby:tabby@db/tabby
    volumes:
      - ./config:/config
    networks:
      - frontend
      - default
    depends_on:
      db:
        condition: 'service_healthy'
  db:
    container_name: rtabby-database
    image: mariadb:latest
    cap_add:		
      - "CAP_CHOWN"
      - "CAP_DAC_OVERRIDE"
      - "CAP_SETGID"
      - "CAP_SETUID"
    cap_drop: ['ALL']
    read_only: true
    tmpfs:
      - /run/mysqld/
      - /tmp
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_MYSQL_LOCALHOST_USER=true
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=tabby
      - MARIADB_USER=tabby
      - MARIADB_PASSWORD=tabby
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 6s
volumes:
  database:
networks:
  default:
    name: rtabby_net_backend
    internal: true
  frontend:
    name: rtabby_net_frontend