CREATE TABLE configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
    name VARCHAR(255) NOT NULL,
    user VARCHAR(255) NULL,
    content MEDIUMTEXT NOT NULL DEFAULT '{}',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);