CREATE TABLE configs (
    id INTEGER auto_increment NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user VARCHAR(255) NULL,
    content TEXT NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1000;

CREATE TABLE user_configs (
    config_id INTEGER NULL REFERENCES configs(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    user VARCHAR(255) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (config_id, user)
);