CREATE TABLE configs (
    id INTEGER auto_increment NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user VARCHAR(255) NULL,
    content MEDIUMTEXT NOT NULL DEFAULT '{}',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1000;