CREATE TABLE configs (
    id INTEGER auto_increment NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user VARCHAR(255) NULL,
    shared INTEGER NULL REFERENCES configs(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    share_hotkey BOOLEAN NOT NULL DEFAULT FALSE,
    share_windows_settings BOOLEAN NOT NULL DEFAULT FALSE,
    share_vault BOOLEAN NOT NULL DEFAULT FALSE,
    content TEXT NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1000;