name: rTabby

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  release:
      types: [published]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Rust Build
    strategy:
      matrix:
        runson: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runson }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose ${{ github.event_name == 'release' && '--release' || '' }}