name: rust-build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  release:
      types: [published]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Rust Build
    strategy:
      matrix:
        runson: [ubuntu-latest, ubuntu-24.04-arm]
        db-backend: [mysql, sqlite]
        login: [local-users, oauth]
        include:
          #arch
          - runson: 'ubuntu-latest'
            arch: 'amd64'
          - runson: 'ubuntu-24.04-arm'
            arch: 'arm64'
          # minimal build
          - login: 'local-users'
            minimal: true
          - login: 'oauth'
            minimal: false

    runs-on: ${{ matrix.runson }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --target-dir target/ci
    - uses: actions/upload-artifact@v4
      # if: ${{ github.event_name == 'release' }}
      with:
        name: ${{ github.repository }}-${{ matrix.arch }}
        path: target/ci/release/rtabby-web-api