name: rust-build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  release:
      types: [published]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Rust/Docker Build
    strategy:
      matrix:
        arch: [amd64, arm64]
        db: [mysql, sqlite]
        login: [local-users, oauth]
        include:
          #runson
          - arch: 'amd64'
            runson: 'ubuntu-latest'
          - arch: 'arm64'
            runson: 'ubuntu-24.04-arm'
          # minimal build
          - login: 'local-users'
            minimal: true
            feature: ''
          - login: 'oauth'
            minimal: false
            feature: '-F all-login'

    runs-on: ${{ matrix.runson }}
    steps:
    - uses: actions/checkout@v4

    - name: Install mysql build dependencies
      if: ${{ matrix.db == 'mysql' }}
      run: sudo apt install libtirpc-dev

    - name: "Cache cargo"
      id: cache-cargo
      uses: "actions/cache@v4"
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.arch }}-${{ matrix.db }}
        restore-keys: ${{ matrix.arch }}-${{ matrix.db }}

    - name: Build
      run: cargo build --verbose --release --target-dir target/ci --no-default-features -F ${{ matrix.db }}-bundle ${{ matrix.feature }}

